#!/usr/bin/python
class Rectangle(object):
    # complete the class definition as described
    
    def __init__(self, length, width):
        self.length = length
        self.width = width
        
    def getArea(self):
        return self.length * self.width
    
    def isSquare(self):
        if self.length == self.width:
            return True
        else:
            return False
        
    def __eq__(self, another):
        return (self.length == another.length) and (self.width == another.width)

# This code tests the functionality of your Rectangle class
if __name__ == '__main__':
    rect1 = Rectangle(10,10)
    rect2 = Rectangle(10,10)
    rect3 = Rectangle(10,15)
    if rect1 == rect2:
        print("Test 1 pass")
    if rect1.isSquare():
        print("Test 2 pass")
    if rect3 == rect1:
        print("Test 3 FAIL")
    else:
        print("Test 3 pass")
